* Usability
** Keyboard Shortcuts
We should add keyboard shortcuts to allow people to quickly edit the model.

This might involve a notion of a /currently selected node/ along with jumplists.

** Tooltips
Process-models are not immediately obvious, and this program is very icon-centric. We expect that users will have had some sort of instruction, but it would still be helpful to have some tooltips.

* Layout
There may be some interest in supporting different layouts. For example, a radial layout with the root at the centre.

** Hyperbolic View
A way to view all the nodes for an arbitrarily large graph at once. This is orthogonal to layout. 

Hyperbolic view does not work very well with highly interconnected graphs: the edges end up criss-crossing the middle.

We can approximate it by applying a hyperbolic transform to the scale and position of each node and edge. This looks ok as long as nodes and edges are small relative to the graph as a whole.

* Maths
The algorithm for combining the failure/success chances (interval probabilities) from multiple pieces of evidence needs review and correction.

See [[file:js/state/combine-evidence.org][the source code]]. It is almost certainly a wrong implementation, but does give very plausible results.

In practice, we do not care that much about correctness here, since any algorithm for this task must make some assumptions to fill in for missing information.

* Performance
In general the performance is acceptable, but it is a little jerky with very large process-models (upwards of 100 nodes).

* Printing
When printing, the process-model isn't positioned as you'd expect. There are probably some special considerations when printing SVGs from the browser.

* Bugs
** Autosave
Auto mode has some bugs. In particular, text editing can lead to a continuous loop of edits bouncing back and forth between browsers.
